#!/bin/bash

# We've got too many parsed files now, so separate in two batches:
/bin/grep -l '.\s\"\s' P*.predict | ./requote.l     # Profiles
/bin/grep -l '.\s\"\s' t*.predict | ./requote.l     # Tweets
